# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 17:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('index', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='PairPreferance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=2)),
                ('date', models.DateField(default=datetime.date(2016, 9, 22))),
                ('time', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('index', models.IntegerField(default=0)),
                ('pic', models.URLField()),
                ('ingredients', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_index', models.IntegerField(default=0)),
                ('dob', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[(b'U', b'Undisclosed'), (b'F', b'Female'), (b'M', b'Male')], default=b'U', max_length=1)),
                ('allergies', models.CharField(default=b'0', max_length=128)),
                ('diet', models.CharField(default=b'0', max_length=128)),
                ('occupation', models.IntegerField(default=0)),
                ('nationality', models.CharField(default=b'0', max_length=128)),
                ('slug', models.SlugField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
