# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2016, 9, 1, 17, 18, 1, 800759, tzinfo=utc)),
        ),
    ]
