# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairpreferance',
            name='browser',
            field=models.CharField(default=b'none', max_length=228),
        ),
        migrations.AddField(
            model_name='pairpreferance',
            name='exp_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairpreferance',
            name='pic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pairpreferance',
            name='scrn_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairpreferance',
            name='scrn_w',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairpreferance',
            name='scroll_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairpreferance',
            name='scroll_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairpreferance',
            name='t_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairpreferance',
            name='t_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pairpreferance',
            name='date',
            field=models.DateField(default=datetime.date(2016, 9, 23)),
        ),
    ]
