# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairpreferance',
            name='u_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pairpreferance',
            name='date',
            field=models.DateField(default=datetime.date(2016, 10, 3)),
        ),
    ]
