# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(max_length=228),
        ),
        migrations.AlterField(
            model_name='pairpreferance',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(max_length=228),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
