# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0002_auto_20160923_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairpreferance',
            name='t_end',
        ),
        migrations.RemoveField(
            model_name='pairpreferance',
            name='t_start',
        ),
        migrations.AddField(
            model_name='pairpreferance',
            name='t_at',
            field=models.CharField(default=b'none', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time_end',
            field=models.CharField(default=b'none', max_length=50),
        ),
    ]
