# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 12:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0003_auto_20160901_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.date(2016, 9, 2)),
        ),
    ]
