# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0003_auto_20160919_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(default=b'0', max_length=128),
        ),
    ]
