# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0004_auto_20160919_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
