# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0005_auto_20160902_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(default='ingredient'),
            preserve_default=False,
        ),
    ]
