# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0005_ingredient_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='time',
        ),
        migrations.AddField(
            model_name='pairpreferance',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
