# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0006_ingredient_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='date',
            field=models.DateField(default=datetime.date(2016, 9, 2)),
        ),
    ]
