# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0007_ingredient_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='date',
        ),
    ]
