# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0008_remove_ingredient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
