# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0012_auto_20160905_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairPreferance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date(2016, 9, 8))),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.date(2016, 9, 8)),
        ),
    ]
