# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0013_auto_20160908_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairpreferance',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
