# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ml', '0014_pairpreferance_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairpreferance',
            name='date',
            field=models.DateField(default=datetime.date(2016, 9, 9)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.date(2016, 9, 9)),
        ),
    ]
